<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Testcontainers" Version="4.9.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Netorrent.Tests\Netorrent.Tests.csproj" />
    <ProjectReference Include="..\Netorrent\Netorrent.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="Data\debian-13.2.0-amd64-netinst.iso.torrent">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Data\MultifileTest\Folder1\Folder2\test3.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Data\MultifileTest\Folder1\test2.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Data\MultifileTest\test.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Data\nosferatu.torrent">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Data\test.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Data\MultifileTest\" />
  </ItemGroup>
</Project>
